# point to the R installation
rsession-which-r=/opt/R/4.5.2/bin/R

# Listen on all interfaces
www-address=0.0.0.0

# Default RStudio Server port
www-port=8787

server-app-armor-enabled=0

# Don’t daemonize (recommended for Docker)
server-daemonize=0
