name: raw

services:

  rstudio:
    build:
      context: .
      dockerfile: rstudio_raw.Dockerfile
    ports:
      - 8787:8787
    volumes:
      - type: bind
        source: ..
        target: /project