name: rstudio-w-packages

services:

  r-studio:
    image: rstudio-gsd
    build:
      context: .
      dockerfile: r-and-install-packages.Dockerfile
    ports:
      - 8787:8787
    volumes:
      - type: bind
        source: ../research-example
        target: /project
    environment:
      - PASSWORD=my-password-here
